GoogleUtilities/Environment/GULHeartbeatDateStorage.m
GoogleUtilities/Environment/Public/GoogleUtilities/GULHeartbeatDateStorage.h
GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageTest.m

• Renaming heartbeat storage directory from "Google/FIRApp" to "GoogleHeartbeatStorage".
• Refactored `GULHeartbeatDateStorage.m` in an effort to make it more readable.
**Context**
`GULHeartbeatDateStorage` related crashes like [this one](https://github.com/firebase/firebase-ios-sdk/issues/7772) may occur because the current heartbeat storage directory is "Google/FIRApp", which makes "Google" the parent directory and  "FIRApp" the child directory.  When `GULHeartbeatDateStorage` instances call `checkAndCreateDirectory:fileCoordinator:` from different threads, the current heartbeat storage directory might be causing blocking issues because `NSFileCoordinator`'s `coordinateWritingItemAtURL:options:error:byAccessor:` method used in `checkAndCreateDirectory:fileCoordinator:` [does not wait …

Change heartbeat directory name and refactor file

---

.github/workflows/test_coverage.yml

The previous setup will always run two jobs,  `Generate report` and `Update New Coverage Data`, in sequence in both presubmit and postsubmit. The workflow will fail while `Generate report` job runs for postsubmit/merge since pr_branch cannot be fetched properly. Also, this job should not run in postsubmit/merge.

Disable jobs when secrets are not available

---

CHANGELOG.md
GoogleUtilities.podspec
GoogleUtilities/Environment/GULHeartbeatDateStorageUserDefaults.m
GoogleUtilities/Environment/Public/GoogleUtilities/GULHeartbeatDateStorable.h
GoogleUtilities/Environment/Public/GoogleUtilities/GULHeartbeatDateStorage.h
GoogleUtilities/Environment/Public/GoogleUtilities/GULHeartbeatDateStorageUserDefaults.h
GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageTest.m
GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageUserDefaultsTest.m

This can be used on tvOS without fear of losing data between launches.
Clients will need to instantiate the class of their choice, then can use the
`GULHeartbeatDateStorable` protocol if they want to mix and match.

Introduce UserDefaults based heartbeat storage.

---

GoogleUtilities/Environment/GULHeartbeatDateStorage.m

This PR **reverts the change** to the heartbeat directory name that was done in #19. 
Logically, the only difference between this PR's change and the head of `main` before changing the heartbeat directory name in #19 should be that the directory name is getting changed from `GoogleHeartbeatStorage` **back to** `Google/FIRApp`.
Relevant files in the diff between this PR's latest commit and head of `main` before #19:
• [GULHeartbeatStorage.m](https://github.com/google/GoogleUtilities/compare/0faf34d4b55fb9d048e2082ebed9fea5e97412e0...bbd4173f76fac863ca4b5fb596b62488cbaeb549#diff-491f83b78a347cd3aac52b47123f5e607bb5c3242ae3c0ab6c0601b77cfb66d9)
• [GULHeartbeatStorage.h](https://github.com/google/GoogleUtilities/compare/0faf34d4b55fb9d048e2082ebed9fea5e97412e0...bbd4173f76fac863ca4b5fb596b6248 …

Revert heartbeat storage directory name (Firebase 8)

---

CHANGELOG.md
Package.swift

To enable GoogleSignIn and iOS 9
Low risk since CocoaPods already supports iOS 9

Support iOS 9 with SwiftPM

---

CHANGELOG.md
GoogleUtilities/Environment/GULHeartbeatDateStorage.m
GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageTest.m
GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m
GoogleUtilities/Tests/Unit/SecureCoding/GULSecureCodingTests.m

Up until now (Xcode 13 beta 1), [property list supported types](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/AboutPropertyLists/AboutPropertyLists.html#//apple_ref/doc/uid/10000048i-CH3-54303) didn't need to be explicitly included in the [class set when unarchiving an object.](https://developer.apple.com/documentation/foundation/nskeyedunarchiver/2962885-unarchivedobjectofclasses?language=objc) From now on however, a warning logs at runtime when an object is unarchived using `NSKeyedUnarchiver` without explicitly mentioning any  plist supported types that are associated with that object's unarchiving.
Fixes [#8276](https://github.com/firebase/firebase-ios-sdk/issues/8276)

Include all object classes when using archiver

---

CHANGELOG.md
GoogleUtilities.podspec
README.md

Next CocoaPods release will jump from 7.4.**1** → 7.4.**3** to account for SwiftPM-only 7.4.**2** release. 
With 7.4.3, both the CP and SPM release will be in sync.
• Updated spec to 7.4.3
• Updated CHANGELOG
• Update release instruction in README

Prep for 7.4.3 release

---

CHANGELOG.md
GoogleUtilities.podspec

I see your comments on GDT PR, I bumped the GULs podspec from 7.4.3 to 7.4.4: https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities.podspec#L3
Should I have bumped 7.5.0?

Fix CHANGELOG.md & Fix #46's spec bump

---

CHANGELOG.md
GoogleUtilities.podspec
GoogleUtilities/Environment/GULHeartbeatDateStorage.m
GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageTest.m

Related to https://github.com/firebase/firebase-ios-sdk/issues/8524
[NSFileCoordinator](https://developer.apple.com/documentation/foundation/nsfilecoordinator?language=objc) behaves unexpectedly (crashes) on some macOS versions. 
`NSFileCoordinator` was used to prevent concurrent access to a storage file from different processes and threads. Initially `GULHeartbeatDateStorage` was designed with intention to share the same heartbeat between an app and its extensions which implies access to a file from different processes. But the sharing was never implemented and there are not immediate plans to do it. It means that `NSFileCoordinator` can be safely replaced by other in-process synchronization mechanisms.
Note that `GULHeartbeatDateStorage` API is currently susceptible to read-modify-write …

GULHeartbeatDateStorage: avoid using NSFileCoordinator

---

CHANGELOG.md
GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
GoogleUtilities/ISASwizzler/GULSwizzledObject.m

~~This just avoids disposing the swizzler's generated classes when zombies is enabled.~~
Fix [#8321](https://github.com/firebase/firebase-ios-sdk/issues/8321)

Set the class of a swizzled object back to its original class upon deallocation.

---

CHANGELOG.md
GoogleUtilities/ISASwizzler/GULSwizzledObject.m

Reverts google/GoogleUtilities#52
Order of operations:

Revert "Set the class of a swizzled object back to its original class upon deallocation."

---

CHANGELOG.md
GoogleUtilities/ISASwizzler/GULObjectSwizzler.m

This is the original fix that checks the env vars for Zombies being enabled. If Zombies is enabled, then the generated class is not disposed
Fix https://github.com/firebase/firebase-ios-sdk/issues/8321

Don't dispose generated classes when Zombies is enabled

---

GoogleUtilities/SwizzlerTestHelpers/GULSwizzlingCache.h

The order of the code documentation params and the the arguments of the methods `cacheCurrentIMP:forNewIMP:forClass:withSelector:` and `cacheCurrentIMP:forNewIMP:forClass:withSelector:` doesn't match. This is fixed now by changing the order of the code documentation.

Fix order of code comments in GULSwizzlingCache

---

GoogleUtilities/ISASwizzler/GULObjectSwizzler.m

Allow to disable generated class dispose calls explicitly, and not only when Zombies instrument is enabled.
That is, to support disabling the dispose calls in special cases which are not Zombie related, for examples: https://github.com/firebase/firebase-ios-sdk/issues/9083, as suggested [here](https://github.com/firebase/firebase-ios-sdk/issues/9083#issuecomment-997182891).

GULObjectSwizzler: allow to disable generated class dispose calls.

---

CHANGELOG.md
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m

Up until this PR, the `+ [GULAppEnvironmentUtil deploymentType]` API has
returned `cocoapods` for non-SwiftPM, non-Carthage, and non-Zip builds. While
such builds can be built via CocoaPods, defaulting to `cocoapods` is not very
precise for cases where the framework is built using other build types (such
as in piper).

[Environment] Update `deploymentType` API to fall back to `unknown` instead of `cocoapods`

---

CHANGELOG.md
Package.swift

I'd need to test it, but I assume the SwiftPM would produce xcframeworks named `GoogleUtilities-Environment.xcframework`, for example.
> edit: import tests passed
I don't think this is breaking because the targets aren't public and the import statement did not change. 
Since the import tests are passing without any additional work, I think that confirms that SwiftPM knows how to generate module names correctly. A target, `GoogleUtilities-Environment`, gets a module that can imported with `import GoogleUtilities_Environment`.
Another option was to remove the underscore so target names would transform between `GoogleUtilities-Environment` → `GoogleUtilitiesEnvironment`. Then, use the module aliasing to prevent the import statement from changing: …

[SwiftPM] Do not use underscores in target names

---

GoogleUtilities/Tests/Unit/Swizzler/GULObjectSwizzlerTest.m

Follow up to #84 
It's still a mystery about why deleting the weak variable causes the test to fail with
```
objc[12242]: objc_disposeClassPair: class 'fir_18AC4DEE-8462-4B19-8F73-9675818BD98F_GULProxy' still has subclasses, including 'gul_test_0x600000c8c0d0_fir_18AC4DEE-8462-4B19-8F73-9675818BD98F_GULProxy'!
```
but this change makes the test consistent with the other tests and actually uses the declared `weakSwizzler` variable.

Add missing test of weak variable

---

GoogleUtilities/Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m

Crashlytics uses this code to display and filter events on the dashboard: 
https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Components/FIRCLSApplication.m#L54
We're hoping to move this code into GoogleUtilities so it can be shared across Crashlytics and Sessions.

Add new App Environment Util for appleDevicePlatform

---

.github/workflows/check.yml
README.md

- Bump clang-format to v15 because https://github.com/llvm/llvm-project/issues/49340
- See https://github.com/firebase/firebase-ios-sdk/pull/10451

[Infra] Bump clang-format to v15

---

GoogleUtilities/Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m

Crashlytics has an important function that returns the device model: [FIRCLSFABHost.m](https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Shared/FIRCLSFABHost.m#L91-L119)
The main purpose of this PR is to share that code with the new FirebaseSessions SDK for the purposes of filtering events consistently between the 2 products, similar to https://github.com/google/GoogleUtilities/pull/89.
There are a few differences between this code and the existing `[GULAppEnvironmentUtil deviceModel]`:
For example, running both methods on a simulator yields the following results:
```
GULAppEnvironmentUtil.deviceModel: arm64
GULAppEnvironmentUtil.deviceSimulatorModel: iOS Simulator (iPhone)
```
Similar to other cases, we're very sensitive to change anything about the Crashlytics …

Add deviceSimulatorModel to GULAppEnvironmentUtil

---

GoogleUtilities.podspec
GoogleUtilities/Environment/NetworkInfo/GULNetworkInfo.m
GoogleUtilities/Environment/Public/GoogleUtilities/GULNetworkInfo.h
GoogleUtilities/Tests/SwiftUnit/GULNetworkInfoTests.swift

Similar to https://github.com/google/GoogleUtilities/pull/90 and https://github.com/google/GoogleUtilities/pull/89, the main purpose of this PR is to share that code with the new FirebaseSessions SDK for the purposes of filtering events consistently between the 2 products.
These functions are utilities for FirebasePerformance to include along with traces for added context to performance issues.
I wasn't totally sure where to put them.
- I put them in GoogleUtilities/Environment because it seemed thematically similar to like determining what's going on with the app in its environment
- They didn't seem to belong in GoogleUtilities/Reachability, but there might be an argument for that
- AppEnvironmentUtil felt overloaded with these added
- GoogleUtilities/Network were mainly for url …

Add Network Utilities to GoogleUtilities

---

GoogleUtilities/Network/GULNetworkURLSession.m

Fix this warning:
- WARN  | [GoogleUtilities/Network,GoogleUtilities/AppDelegateSwizzler] xcodebuild:  /Users/paulbeusterien/github/GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m:511:37: warning: 'backgroundSessionConfiguration:' is deprecated: first deprecated in watchOS 2.0 [-Wdeprecated-declarations]

Fix build warning by deleting unsupported old OS code

---

GoogleUtilities/Environment/NetworkInfo/GULNetworkInfo.m

Fix #97 
Enable GoogleUtilities to build without warnings when the minimum iOS version is changed from the project default.

Address iOS 12 deprecation warnings

---

CHANGELOG.md
GoogleUtilities/Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h
GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m

Upon merging, I will do an internal copybara to smoke test and then publish a SwiftPM-only patch release. This change is backwards compatible, as proven by CI.

[Environment] Calling `+[GULAppEnvironmentUtil applePlatform]` returns visionOS specific value

---

GoogleUtilities/Network/GULNetworkURLSession.m

See https://github.com/firebase/firebase-ios-sdk/issues/11536 for details. Xcode 15 Beta 3 introduces a runtime warning when creating an upload task from a URL request that _contains_  a non-nil HTTPBody field. I can't find any reasoning as to why this is now a warnings, but it looks like URL request objects should only contain metadata about the request, not the data itself.
Fix https://github.com/firebase/firebase-ios-sdk/issues/11536
After merging, will open a new PR with a changelog update and podspec bump. We can do a CocoaPods + SPM release for this. This will align the two, since we have done some SPM-only releases in the time since the last CocoaPods release. 
cc: @htcgh, @pcfba

[Network] Resolve Xcode 15 Beta 4 runtime warning

---

GoogleUtilities.podspec

This is to address an issue similar to https://github.com/firebase/firebase-ios-sdk/issues/9781. 
The pod has `Apache-2.0` license mentioned in the [LICENSE](https://github.com/google/GoogleUtilities/blob/main/LICENSE).
But, the podspec file sets :license :type as `Apache`
This correction ensures alignment with the correct license, making it consistent and accurate.

Changing podspec file's license from Apache to Apache-2.0

---

LICENSE

This text gets flagged by internal checks for being "unidentified". I think it's safe to remove. It is also outdated as we've changed the referenced file path.

[Infra] Remove more non-license text

---

GoogleUtilities/AppDelegateSwizzler/Public/GoogleUtilities/GULApplication.h
GoogleUtilities/Environment/GULAppEnvironmentUtil.m

In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1`. This PR fixes the build on visionOS (and resolves #130) but does not address all issues in tests.
In follow-ups we should audit uses of `TARGET_OS_IOS` throughout the codebase.

Fix visionOS build in Xcode 15.1 beta 1

---

GoogleUtilities/Reachability/GULReachabilityChecker.m

In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1`. This PR fixes [GULReachabilityCheckerTest](https://github.com/google/GoogleUtilities/blob/4780d5c011278da93839a4cef27d3cec9efa3938/GoogleUtilities/Tests/Unit/Reachability/GULReachabilityCheckerTest.m) when running on the Apple Vision Pro simulator.

[visionOS] Fix `GULReachabilityCheckerTest` in Xcode 15.1 beta 1

---

Gemfile
Gemfile.lock

Updated to CocoaPods 1.14.0 to match https://github.com/firebase/firebase-ios-sdk/pull/12008.

Update CocoaPods to v1.14.0

---

CHANGELOG.md
Package.swift

Underscore in target name should instead be a dash.
Fixes #140

[SwiftPM] Fix target with invalid name

---

GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m

A couple observations while trying to reproduce.
- The test fails in what appears to be random fashion. When it fails, it's due to an uncaught exception. I'm not sure where it's coming from but I suspect it may be OCMock related... not sure
- It _seems_ like disabling xcpretty in the invocation increases the chance of it crashing
- It is not reproducible in Xcode
- invocation: `../firebase-ios-sdk/scripts/test_catalyst.sh GoogleUtilities test GoogleUtilities-Unit-unit`
CI is green though I'm not super convinced this will work. See #120 for alt. approach that does some code cleanup.

[Infra] Fix flaky 'NSURLSession+GULPromises' test

---

.github/workflows/check.yml
Gemfile
Gemfile.lock
GoogleUtilities/Tests/Unit/UserDefaults/GULUserDefaultsTests.m
SwiftPMTests/swift-test/main.swift

- Update default CocoaPods version
- Fix unreachable warning in test build
- Fix device check

CI fixes now that default runners can be arm64

---

GoogleUtilities/AppDelegateSwizzler/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/Environment/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/ISASwizzler/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/Logger/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/MethodSwizzler/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/NSData+zlib/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/Network/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/Reachability/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/UserDefaults/Resources/PrivacyInfo.xcprivacy
Package.swift

With this PR, the privacy manifest approach is as follows:
- [changed] SwiftPM library targets have corresponding, unique privacy manifests
- [unchanged] CocoaPods subspaces share dependency on a common, aggregated privacy manifest

[Infra] Refactor privacy manifests to address #150

---

GoogleUtilities/Network/GULNetworkURLSession.m
GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m

A duplicate issue to the one resolved in #114 just in the `then` part of the same `if`
Also revert #157 since the Catalyst flake just moved to the previous test. Something about the last Promises test doesn't work?

Fix Xcode 15 runtime warning

---

GoogleUtilities/Environment/GULAppEnvironmentUtil.m
GoogleUtilities/Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h

[Cleanup] Remove '+ [GULAppEnvironmentUtil hasSwiftRuntime]' API

---

CHANGELOG.md
GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m

Now only `application:didReceiveRemoteNotification:fetchCompletionHandler:` is supported unconditionally.
Without removing the conditional around the new API, Firebase would not be able to drop support for the old API.
Part of the solution for https://github.com/firebase/firebase-ios-sdk/issues/11693
This is a breaking change and should wait for version 8.

Remove support for deprecated application:didReceiveRemoteNotification:

---

CHANGELOG.md
GoogleUtilities/ISASwizzler/GULObjectSwizzler+Internal.h
GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
GoogleUtilities/ISASwizzler/GULSwizzledObject.m
GoogleUtilities/ISASwizzler/Public/GoogleUtilities/GULObjectSwizzler.h
GoogleUtilities/Tests/Unit/Swizzler/GULObjectSwizzlerTest.m

From the [Foundation docs for `-[NSString UTF8String]`](https://developer.apple.com/documentation/foundation/nsstring/1411189-utf8string?language=objc):
>This C string is a pointer to a structure inside the string object, which may have a lifetime shorter than the string object and will certainly not have a longer lifetime. Therefore, you should copy the C string if it needs to be stored outside of the memory context in which you use this property.
Since the inner pointer may have a shorter lifespan than the owning NSString, it shouldn't be used as a constant value. This PR replaces it with the address of the variable, which is guaranteed to be constant during the lifetime of the string constant.

Use guaranteed const for associated object key

---

GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m

The promises tests consistently flake on catalyst. Weirdly, it's always the last test to run that flakes. 
Opened a bug to track: https://github.com/google/GoogleUtilities/issues/170

[Infra] Disable NSURLSession+GULPromisesTests.m for Catalyst

---

GoogleUtilities/Environment/Public/GoogleUtilities/GULKeychainStorage.h
GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m

Address https://github.com/google/GoogleUtilities/pull/187#discussion_r1635183501

[v8] Remove extraneous parameter from removeObject API

---

GoogleUtilities/Environment/NetworkInfo/GULNetworkInfo.m

Taking same approach to what is done in GDT: 
https://github.com/google/GoogleDataTransport/blob/e6d2576c9d1910bf92739c907aa544e1cdb29982/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m#L133-L141

[v8] Replaced deprecated network info API

---

GoogleUtilities/Tests/Unit/UserDefaults/GULUserDefaultsTests.m
GoogleUtilities/UserDefaults/GULUserDefaults.m
GoogleUtilities/UserDefaults/Public/GoogleUtilities/GULUserDefaults.h

With the min. OS version matrix moving to iOS 12.0+, the iOS 11.0 (https://github.com/firebase/firebase-ios-sdk/pull/1812#issue-359943861) bug where the user-defaults-spawned notification causes an app crash is no longer relevant. The bug was fixed but there likely were unfixed versions of iOS 11.0 where the CFPreferences implementation was still needed.

[v8] Replace CFPreferences with NSUserDefaults

---

GoogleUtilities/Environment/Resources/PrivacyInfo.xcprivacy
GoogleUtilities/Privacy/Resources/PrivacyInfo.xcprivacy

The need for the [1C8F.1 reason](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#:~:text=1C8F.1,same%20App%20Group.) was removed with the removal of the `GULHeartbeatDateStorage` class in v8 (#164).

[v8] Update privacy manifest for v8

---

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/AppDelegateSwizzler/Public/GoogleUtilities/GULApplication.h
GoogleUtilities/Environment/GULAppEnvironmentUtil.m
GoogleUtilities/Reachability/GULReachabilityChecker.m
GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m

1. Remove `defined(TARGET_OS_VISION)`
2. `TARGET_OS_IOS && !TARGET_OS_VISION` can be simplified to `TARGET_OS_IOS`
-  See https://github.com/firebase/firebase-ios-sdk/pull/13184#issue-2373645638

[NFC] Remove unneccessary visionOS #if logic

---

Package.swift

The dependency on https://github.com/google/promises is no longer needed.

Remove `Promises` dependency in SPM

---

GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
GoogleUtilities/AppDelegateSwizzler/GULSceneDelegateSwizzler.m
GoogleUtilities/Logger/GULLogger.m
GoogleUtilities/Logger/Public/GoogleUtilities/GULLogger.h
GoogleUtilities/Logger/Public/GoogleUtilities/GULLoggerLevel.h
GoogleUtilities/MethodSwizzler/GULSwizzler.m
GoogleUtilities/Network/GULNetwork.m
GoogleUtilities/Network/GULNetworkURLSession.m
GoogleUtilities/Reachability/GULReachabilityChecker.m
GoogleUtilities/Tests/Unit/Logger/GULLoggerTest.m
GoogleUtilities/UserDefaults/GULUserDefaults.m

Migrated from `ASL` to `OSLog` in `GULLogger` but retained the existing API (now deprecated) for backwards compatibility.

Migrate from `ASL` to `OSLog`

---

GoogleUtilities.podspec

I think the modern linkers may find these without declaration, but just in case, and for consistency
Note, that we don't declare any framework deps in Package.swift

Add OSLog to podspec

---

GoogleUtilities.podspec

This reverts commit 493b5a0d33a5d76819034c3396a5a50140af4b06. No longer needed with https://github.com/google/GoogleUtilities/pull/203.

Revert "Add OSLog to podspec (#201)"

---

GoogleUtilities/Logger/GULLogger.m

Removed an extraneous `#undef GUL_LOGGING_FUNCTION` (leftover from the macro for the deprecated functions -- already deleted).

Remove leftover `#undef GUL_LOGGING_FUNCTION`

---

.swiftformat
GoogleUtilities/Tests/SwiftUnit/GULAppEnvironmentUtilTest.swift

The code formatting script from https://github.com/firebase/firebase-ios-sdk/blob/main/scripts/style.sh now expects the Swift formatting options to be in a `.swiftformat` file as of https://github.com/firebase/firebase-ios-sdk/pull/13423.

Move SwiftFormat options to a config file

---

GoogleUtilities/Logger/GULLogger.m

Setting a default logger level (`sGULLoggerMaximumLevel`) was erroneously removed in [#192](https://github.com/google/GoogleUtilities/pull/192/files#diff-87f09690a8bbc2864d7384f85b7a75f1326306f1c925317800731fffd96dd91eL66) and, prior to this PR, had a value of `0` instead of `GULLoggerLevelNotice` (`5`) resulting in no logging without `-FIRDebugEnabled`. This re-adds the deleted line in `GULLoggerInitialize()`.

Set default logger level to `GULLoggerLevelNotice`

---

.github/workflows/check.yml
GoogleUtilities/MethodSwizzler/Public/GoogleUtilities/GULOriginalIMPConvenienceMacros.h

This simplifies things by getting clang-format from the firebase-ios-sdk checkout during CI rather than from this repo.
Corresponding GoogleDataTransport PR: https://github.com/google/GoogleDataTransport/pull/157

[Infra] Prefer `setup_check.sh` over manual config

---

GoogleUtilities/Environment/GULAppEnvironmentUtil.m
GoogleUtilities/Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h

This adds two utility functions to `GULAppEnvironmentUtil.m`:
- `isAppClip`, which determines heuristically whether the current app is an App Clip. I do not think it's necessarily _required_ that app clips have this top level dictionary in their Info.plist, but in practice I would assume almost all do.
- `supportsBackgroundURLSessionUploads`, which checks both for app extensions and app clips and turns off background uploads for both of them.
I have submitted [a separate PR to `firebase-ios-sdk`](https://github.com/firebase/firebase-ios-sdk/pull/14794) to make use of `supportsBackgroundURLSessionUploads`, because as of now [AppClips fail when uploading files](https://github.com/firebase/firebase-ios-sdk/issues/14793).

Add a utility to detect App Clips and make a semantic check for background URL sessions

---

.github/workflows/google-utilities.yml

The macos-15 runner image lacks the iOS 18.2 simulator runtime for Xcode 16.2, causing CI jobs to fail.
This adds a workflow step to explicitly download the required simulator, ensuring tests can run with the minimum supported Xcode version.

fix(ci): install missing iOS 18.2 simulator runtime
