- README.md
To be confirmed the first time we need to do this.
> Add integration testing and publishing instructions

- .github/workflows/google-utilities.yml
- Package.swift
Addressing https://github.com/firebase/firebase-ios-sdk/issues/7405
> Namespace products

- CHANGELOG.md
- GoogleUtilities.podspec
- GoogleUtilities/Logger/GULLogger.m
- Package.swift
Also minor changelog and SPM manifest cleanup
> Fix Xcode 12.5 build warnings

- CHANGELOG.md
- GoogleUtilities/ISASwizzler/GULObjectSwizzler+Internal.h
- GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
- GoogleUtilities/ISASwizzler/GULSwizzledObject.m
- GoogleUtilities/ISASwizzler/Public/GoogleUtilities/GULSwizzledObject.h
- GoogleUtilities/Tests/Unit/Swizzler/GULObjectSwizzlerTest.m
Fixes https://github.com/firebase/firebase-ios-sdk/issues/7635.
> Add prefix to constant name to avoid name conflicts

- CHANGELOG.md
- GoogleUtilities.podspec
- missing dependency was detected in cl/356589674
> Add explicit dependency on Security framework to Environment subspec

- GoogleUtilities.podspec
• Updating podspec to patch in changes from #19
• CHANGELOG has been updated as well f189407
> Update podspec version to 7.3.2

- GoogleUtilities.podspec
Bump spec version from `7.4.1` → `7.4.2`
> Update spec for 7.4.2 release

- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/AppDelegateSwizzler/GULSceneDelegateSwizzler.m
> Apply clang-format version 12.0.1 style

- GoogleUtilities.podspec
Forgot to do this in #52 
#no-changelog
> Bump podspec for 7.5.2 integration testing

- Mintfile
> Upgrade swift-format to match firebase-ios-sdk

- .github/workflows/check.yml
- CHANGELOG.md
- GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m
- GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m
- GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m
- GoogleUtilities/Tests/Unit/Logger/GULLoggerTest.m
- GoogleUtilities/Tests/Unit/Network/GULNetworkTest.m
- GoogleUtilities/Tests/Unit/Shared/URLSession/FIRURLSessionOCMockStub.m
- GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m
- GoogleUtilities/Tests/Unit/Swizzler/GULSceneDelegateSwizzlerTest.m
- GoogleUtilities/Tests/Unit/UserDefaults/GULUserDefaultsTests.m
- Package.swift
- README.md
Fix https://github.com/firebase/firebase-ios-sdk/issues/9591
> Use same OCMock as Firebase

- .github/workflows/check.yml
- Unblocks `check` workflow in #75 
#no-changelog
> [Infra] Remove module imports check

- .github/workflows/check.yml
- .github/workflows/google-utilities.yml
- .github/workflows/spm.yml
- .github/workflows/test_coverage.yml
The GUL equivalent of https://github.com/firebase/firebase-ios-sdk/pull/9498
#no-changelog
> [Infra] Add cancel-in-progress feature to GHA

- GoogleUtilities.podspec
Successor to #75
#no-changelog
> [v7.8.0] Bump podspec version for 7.8.0 release

- GoogleUtilities/Tests/Unit/Swizzler/GULObjectSwizzlerTest.m
> Fix SPM and internal MALLOC_SCRIBBLE test failure

- GoogleUtilities/Logger/GULLogger.m
> Fix release config unused warning

- CHANGELOG.md
- GoogleUtilities.podspec
Also notice the podspec wasn't updated from last release. Is this ideal?
> update changelog for 7.10.0 release

- CHANGELOG.md
- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m
Tracking open questions in https://github.com/google/GoogleUtilities/issues/109
> [visionOS] Fix visionOS build errors on Xcode 15.0 Beta 2 

- GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
- GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
- GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m
- GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m
`git grep --name-only 'TARGET_OS_XR' | xargs sed -i '' 's/TARGET_OS_XR/TARGET_OS_VISION/g' `
cc: @andrewheard
> [visionOS] Replace 'TARGET_OS_XR' with 'TARGET_OS_VISION'

- CHANGELOG.md
- GoogleUtilities.podspec
Post merge, I will stage the pod to staging.
> [Release] Update podspec and changelog for 7.11.5 release

- LICENSE
Remove documentation from LICENSE text. This text is included in the source and does not seem part of the LICENSE text.
> [Infra] Update LICENSE

- GoogleUtilities/Logger/GULLogger.m
- GoogleUtilities/Logger/Public/GoogleUtilities/GULLogger.h
- GoogleUtilities/Tests/Unit/Logger/GULLoggerTest.m
Added a getter for the current logging level `GULGetLoggerLevel`.
> [Logger] Add GULGetLoggerLevel function

- CHANGELOG.md
- GoogleUtilities.podspec
> [Release] Bump spec to 7.13.0 and add changelog entry

- CHANGELOG.md
- GoogleUtilities.podspec
- GoogleUtilities/UserDefaults/GULUserDefaults.m
Testing this out. IIUC, I don't think the delay is needed anymore.
context: b/129719759
> [UserDefaults] Remove delayed synchronization

- GoogleUtilities/Environment/GULSecureCoding.m
- GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h
> [Environment] Rename parameter to avoid conflict with keyword

- .github/workflows/google-utilities.yml
> Fix id name in change check

- GoogleUtilities/Tests/Unit/Environment/NSURLSession+GULPromisesTests.m
Merge main into release-8.0 for cleaner CI runs
> [Infra] Disable NSURLSession+GULPromisesTests.m for Catalyst (#167)

- Package.swift
Made an issue to remind us to ensure it stays in sync https://github.com/google/GoogleUtilities/issues/173
> [Infra] Bump package manifest's tool version

- GoogleUtilities/ISASwizzler/Public/GoogleUtilities/GULSwizzledObject.h
- GoogleUtilities/Logger/Public/GoogleUtilities/GULLoggerLevel.h
- GoogleUtilities/MethodSwizzler/Public/GoogleUtilities/GULOriginalIMPConvenienceMacros.h
- GoogleUtilities/NSData+zlib/GULNSData+zlib.m
- GoogleUtilities/NSData+zlib/Public/GoogleUtilities/GULNSData+zlib.h
- GoogleUtilities/Network/GULNetwork.m
- GoogleUtilities/Network/Public/GoogleUtilities/GULMutableDictionary.h
- GoogleUtilities/Network/Public/GoogleUtilities/GULNetwork.h
- GoogleUtilities/Network/Public/GoogleUtilities/GULNetworkConstants.h
- GoogleUtilities/Network/Public/GoogleUtilities/GULNetworkLoggerProtocol.h
- GoogleUtilities/Network/Public/GoogleUtilities/GULNetworkMessageCode.h
- GoogleUtilities/Reachability/Public/GoogleUtilities/GULReachabilityChecker.h
- GoogleUtilities/Tests/Unit/Network/GULNetworkTest.m
- GoogleUtilities/Tests/Unit/Reachability/GULReachabilityCheckerTest.m
> [v8] Add nullabilty annotations to public headers

- GoogleUtilities/Environment/Public/GoogleUtilities/GULKeychainStorage.h
- GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
I'm merging into a feature branch off of the v8 branch. I'm breaking the work into smaller PRs to make each API re-write easier to review.
> [v8] Replace read keychain API with completion handler based API

- GoogleUtilities/Environment/Public/GoogleUtilities/GULKeychainStorage.h
- GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
Merging into [nc/remove-promises](https://github.com/google/GoogleUtilities/tree/nc/remove-promises).
> [v8] Replace remove keychain API with completion handler based API

- GoogleUtilities/Environment/Public/GoogleUtilities/GULKeychainStorage.h
- GoogleUtilities/Environment/SecureStorage/GULKeychainStorage.m
- GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m
fix style, fix docs, fix unit tests
> [v8] Fix tests, docs, and imports following `GULKeychainStorage` API changes

- GoogleUtilities/Network/GULNetworkURLSession.m
Part of effort to close out #176
> [v8] Fix deprecation in GULNetworkURLSession.m

- CHANGELOG.md
- GoogleUtilities.podspec
Updated the podspec version in preparation for an 8.0.2 release.
> [v8.0.2] Update GoogleUtilities.podspec version

- README.md
> [Infra] Update README.md code formatting docs
